#!/bin/sh


DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
AppDIR=/usr/share/applications
MainDIR="$(dirname $DIR)"
MainDIR="$(dirname $MainDIR)"
WorkingDIR=$MainDIR/extensions.d/app-folder

export Type=user

source $MainDIR/ressources.d/variables


while [ true ]
do

sleep 2


	
	if [ -d "$WorkingDIR" ]; then
		
		CheckApps="$(get_var CheckApps)"
		        
        	if [ ! "$CheckApps" = "true" ]
		then
			
			CountDEF=$(ls -l $WorkingDIR/default/ | wc -l)
			
			write_var CountOLD $CountDEF
                	write_var CheckApps true
	
		fi

			
                source $MainDIR/ressources.d/variables
		
		CountNOW=$(ls -l $AppDIR | wc -l)
                CountOLD="$(get_var CountOLD)"
					
		if [ ! "$CountOLD" = "$CountNOW" ]
		then
			
			diff $AppDIR $WorkingDIR/default/ | grep $AppDIR | awk '{print $4}' > $HOME/.config/rune/app-folder-plus
               		GSET=$(cat $HOME/.config/rune/app-folder-plus)
               		GSET=$(echo $GSET  | sed 's/. /!/g')
               		GSET=$(echo ${GSET//!/\',\'})
               		GSET=$(echo ${GSET/%./\'\]\"})
			GSET=$(echo ${GSET/#/gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Install/ apps \"\[\'})
			echo $GSET > /tmp/app-folder-plus
			chmod +x /tmp/app-folder-plus
			/tmp/app-folder-plus
			rm /tmp/app-folder-plus
			write_var CountOLD $CountNOW
		
		fi

	fi


done

























# Ding Dong Motherfucker!
