#!/bin/bash

SCRIPTPATH=/etc/mudskipper/Script

#########################
#Remove Configuration	#
#########################


rm -R /usr/share/backgrounds
rm -R /usr/share/gnome-background-properties


#########################
#Install Packages	#
#########################


cp -Rf $SCRIPTPATH/2_Packages/*/* /	
systemctl enable mudskipper.service

