#!/bin/bash

USER=
pacman -S --noconfirm sudo

function changepass {

if [ "$answer" = "y" ]
then
        CHECK=false

        while [ "$CHECK" = "false" ]
        do

        /1_Installation/1_Script/ui/clear
        echo ---------------
        echo Enter Password:
        echo ---------------
        read -s PASS1
        /1_Installation/1_Script/ui/clear
        echo ----------------
        echo Repeat Password:
        echo ----------------
        read -s PASS2

                if [ ! "$PASS1" = "$PASS2" ]
                then

                        /1_Installation/1_Script/ui/clear
                        echo -----------------------
                        echo Password doesn\'t match
                        echo -----------------------
                else
                        CHECK=true
                        echo $USER:$PASS1 | chpasswd
                        PASS1=1
                        PASS2=2
                        /1_Installation/1_Script/ui/clear
                        echo ------------
                        echo Password Set
                        echo ------------
                        sleep 1
                fi
        done
fi
}






#########################
#Setup Existing User	#
#########################

/1_Installation/1_Script/ui/clear


CLONE=false
EXIST=false

while [ "$CLONE" = "false" ]
do

	echo -------------------------------
	echo Clone an existing User? \(y/n\)
	echo -------------------------------
	read answer
	echo
	
	while [ "$answer" = "n" ]
	do
	CLONE=true	
	answer=o
	done
	
	while [ ! "$answer"  = "y" -a ! "$answer" = "n" -a ! "$answer" = "o"  ]
	do

		/1_Installation/1_Script/ui/clear
		echo --------------------------------------------
		echo I could not read your answer. Please repeat.
		echo Clone an existing user? \(y/n\)
		echo --------------------------------------------
		read answer
	done


	while [ "$answer" = "y" ]
	do
		/1_Installation/1_Script/ui/clear
                ls /1_Installation/3_Bind
		echo ---------------------
		echo Select user to clone:
		echo ---------------------
        	read USER
		
		if [ ! -d "/1_Installation/3_Bind/$USER" ]; then
			
			/1_Installation/1_Script/ui/clear
        		/1_Installation/1_Script/ui/info 5 User\ \"$USER\"\ doesn\’t\ exist.
        		
			CLONE=false
			answer=n
		else
	
			CLONE=true
			EXIST=true
			
			
			useradd -m -G wheel -s /bin/bash ${USER}
			changepass   
        		/1_Installation/1_Script/ui/clear
			




			gpasswd -a $USER wheel
			gpasswd -a $USER audio
			gpasswd -a $USER video
			gpasswd -a $USER games
			gpasswd -a $USER power
			
			INPATH=/1_Installation/3_Bind/$USER
			/1_Installation/1_Script/ui/clear
			echo ---------------------------------
			echo Copy personal files. Please Wait.
			echo ---------------------------------

			cp -R $INPATH/* /home/$USER
			
			/1_Installation/1_Script/ui/clear
			echo --------------------------------------
			echo Copy configuration files. Please Wait.
			echo --------------------------------------


			cp -R $INPATH/.thunderbird /home/$USER &> /dev/null


			chown -R $USER /home/$USER
			
			/1_Installation/1_Script/ui/clear
			
			echo -------------------------
			echo Clone next User? \(y/n\)
        		echo -------------------------
			read answer

		fi
	done	
done



#########################
#Setup New User		#
#########################





/1_Installation/1_Script/ui/clear
echo --------------------------
echo Create a new User? \(y/n\)
echo --------------------------
read answer


while [ "$EXIST" = "false" -o "$answer" = "y" ] 
do



	while [ "$answer"  = "n" -a "$EXIST" = "false" ]
	do

	/1_Installation/1_Script/ui/clear
	echo ----------------------------------------------------
	echo You need at minimum one user to install this System.
	echo So please enter \(y\).
	echo ----------------------------------------------------
	read answer

	done





	while [ ! "$answer"  = "y" -a ! "$answer" = "n" ]
	do

		/1_Installation/1_Script/ui/clear
		echo --------------------------------------------
		echo I could not read your answer. Please repeat.
		echo Create a new user? y/n
		echo --------------------------------------------
		read answer
	done


	while [ "$answer" = "y" ]
	do

		/1_Installation/1_Script/ui/clear
		echo --------------
		echo Enter username
		echo --------------
		read USER
		
		useradd -m -G wheel -s /bin/bash ${USER}
		changepass
		EXIST=true

		gpasswd -a $USER wheel
		gpasswd -a $USER audio
		gpasswd -a $USER video
		gpasswd -a $USER games
		gpasswd -a $USER power
		
		/1_Installation/1_Script/ui/clear
		echo ---------------------
		echo Create next User? y/n
		echo ---------------------
        	read answer
	done

done

echo
echo %wheel ALL=\(ALL\) ALL >> /etc/sudoers



#########################
#Set Root Password	#
#########################

USER=root

/1_Installation/1_Script/ui/clear
echo -----------------------------
echo Set a root Password? \(y\/n\)
echo -----------------------------
read answer

changepass
