#!/bin/sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
APPDIR=/usr/share/applications
MainDIR="$(dirname $DIR)"
MainDIR="$(dirname $MainDIR)"
WorkingDIR=$MainDIR/extensions.d/app-folder/default


source $MainDIR/ressources.d/variables

CopyApps="$(get_var CopyApps)"


if [ !  "$CopyApps" == "true" ]; then

	mkdir -p $WorkingDIR
	cp -R $APPDIR/* $WorkingDIR
	echo CopyApps=true > $DIR/config
	source $DIR/config &> /dev/null
        write_var CopyApps true


fi


