#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1="\[\e[1m\]--------
\[\e[0;32m\]\T \w
\[\e[1;34m\]\u@\H - \[\e[0;34m\]\[\e[0m\]"

