#!/bin/sh

DIR="$( cd  "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
MainDIR="$(dirname $DIR)"
MainDIR="$(dirname $MainDIR)"
ExteDIR="$(echo $MainDIR/extensions.d/bash-profile-mudskipper)"

export Type=user
  
source $MainDIR/ressources.d/variables


BashProfile="$(get_var BashProfile)"



if [ ! "$BashProfile" = "true" ]
then
	
	
	write_var BashProfile true
	cp $ExteDIR/bashrc $HOME/.bashrc

	
fi




